type Materia @aws_iam @aws_cognito_user_pools {
  nombre: String!
  profesorId: String!
  grupos(filter: ModelGrupoFilterInput, sortDirection: ModelSortDirection, limit: Int, nextToken: String): ModelGrupoConnection
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String
}

type Grupo @aws_iam @aws_cognito_user_pools {
  nombre: String!
  materiaId: ID!
  materia: Materia
  adminId: String!
  integrantes: [String]
  cards(filter: ModelCardFilterInput, sortDirection: ModelSortDirection, limit: Int, nextToken: String): ModelCardConnection
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String
}

type Card @aws_iam @aws_cognito_user_pools {
  titulo: String!
  descripcion: String
  estado: CardEstado
  orden: Int
  grupoId: ID!
  grupo: Grupo
  adjuntos: [String]
  puntuacion: Int
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String
}

type LogActividad @aws_iam @aws_cognito_user_pools {
  grupoId: ID!
  usuarioId: String!
  accion: String!
  entidad: String!
  entidadId: String!
  timestamp: AWSTimestamp!
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String
}

enum CardEstado {
  backlog
  progreso
  revision
  hecho
}

input AmplifyAIConversationTurnErrorInput {
  errorType: String!
  message: String!
}

input ModelStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelBooleanInput {
  ne: Boolean
  eq: Boolean
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelSubscriptionStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  in: [String]
  notIn: [String]
}

input ModelSubscriptionIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  in: [Int]
  notIn: [Int]
}

input ModelSubscriptionFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  in: [Float]
  notIn: [Float]
}

input ModelSubscriptionBooleanInput {
  ne: Boolean
  eq: Boolean
}

input ModelSubscriptionIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  in: [ID]
  notIn: [ID]
}

enum ModelAttributeTypes {
  binary
  binarySet
  bool
  list
  map
  number
  numberSet
  string
  stringSet
  _null
}

input ModelSizeInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
}

enum ModelSortDirection {
  ASC
  DESC
}

type ModelMateriaConnection @aws_iam @aws_cognito_user_pools {
  items: [Materia]!
  nextToken: String
}

input ModelMateriaFilterInput {
  nombre: ModelStringInput
  profesorId: ModelStringInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelMateriaFilterInput]
  or: [ModelMateriaFilterInput]
  not: ModelMateriaFilterInput
  owner: ModelStringInput
}

type Query {
  getMateria(id: ID!): Materia @aws_iam @aws_cognito_user_pools
  listMaterias(filter: ModelMateriaFilterInput, limit: Int, nextToken: String): ModelMateriaConnection @aws_iam @aws_cognito_user_pools
  getGrupo(id: ID!): Grupo @aws_iam @aws_cognito_user_pools
  listGrupos(filter: ModelGrupoFilterInput, limit: Int, nextToken: String): ModelGrupoConnection @aws_iam @aws_cognito_user_pools
  getCard(id: ID!): Card @aws_iam @aws_cognito_user_pools
  listCards(filter: ModelCardFilterInput, limit: Int, nextToken: String): ModelCardConnection @aws_iam @aws_cognito_user_pools
  getLogActividad(id: ID!): LogActividad @aws_iam @aws_cognito_user_pools
  listLogActividads(filter: ModelLogActividadFilterInput, limit: Int, nextToken: String): ModelLogActividadConnection @aws_iam @aws_cognito_user_pools
}

input ModelMateriaConditionInput {
  nombre: ModelStringInput
  profesorId: ModelStringInput
  and: [ModelMateriaConditionInput]
  or: [ModelMateriaConditionInput]
  not: ModelMateriaConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  owner: ModelStringInput
}

input CreateMateriaInput {
  nombre: String!
  profesorId: String!
  id: ID
}

input UpdateMateriaInput {
  nombre: String
  profesorId: String
  id: ID!
}

input DeleteMateriaInput {
  id: ID!
}

type Mutation {
  createMateria(input: CreateMateriaInput!, condition: ModelMateriaConditionInput): Materia @aws_iam @aws_cognito_user_pools
  updateMateria(input: UpdateMateriaInput!, condition: ModelMateriaConditionInput): Materia @aws_iam @aws_cognito_user_pools
  deleteMateria(input: DeleteMateriaInput!, condition: ModelMateriaConditionInput): Materia @aws_iam @aws_cognito_user_pools
  createGrupo(input: CreateGrupoInput!, condition: ModelGrupoConditionInput): Grupo @aws_iam @aws_cognito_user_pools
  updateGrupo(input: UpdateGrupoInput!, condition: ModelGrupoConditionInput): Grupo @aws_iam @aws_cognito_user_pools
  deleteGrupo(input: DeleteGrupoInput!, condition: ModelGrupoConditionInput): Grupo @aws_iam @aws_cognito_user_pools
  createCard(input: CreateCardInput!, condition: ModelCardConditionInput): Card @aws_iam @aws_cognito_user_pools
  updateCard(input: UpdateCardInput!, condition: ModelCardConditionInput): Card @aws_iam @aws_cognito_user_pools
  deleteCard(input: DeleteCardInput!, condition: ModelCardConditionInput): Card @aws_iam @aws_cognito_user_pools
  createLogActividad(input: CreateLogActividadInput!, condition: ModelLogActividadConditionInput): LogActividad @aws_iam @aws_cognito_user_pools
  updateLogActividad(input: UpdateLogActividadInput!, condition: ModelLogActividadConditionInput): LogActividad @aws_iam @aws_cognito_user_pools
  deleteLogActividad(input: DeleteLogActividadInput!, condition: ModelLogActividadConditionInput): LogActividad @aws_iam @aws_cognito_user_pools
}

input ModelSubscriptionMateriaFilterInput {
  nombre: ModelSubscriptionStringInput
  profesorId: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionMateriaFilterInput]
  or: [ModelSubscriptionMateriaFilterInput]
  owner: ModelStringInput
}

type Subscription {
  onCreateMateria(filter: ModelSubscriptionMateriaFilterInput, owner: String): Materia @aws_subscribe(mutations: ["createMateria"]) @aws_iam @aws_cognito_user_pools
  onUpdateMateria(filter: ModelSubscriptionMateriaFilterInput, owner: String): Materia @aws_subscribe(mutations: ["updateMateria"]) @aws_iam @aws_cognito_user_pools
  onDeleteMateria(filter: ModelSubscriptionMateriaFilterInput, owner: String): Materia @aws_subscribe(mutations: ["deleteMateria"]) @aws_iam @aws_cognito_user_pools
  onCreateGrupo(filter: ModelSubscriptionGrupoFilterInput, owner: String): Grupo @aws_subscribe(mutations: ["createGrupo"]) @aws_iam @aws_cognito_user_pools
  onUpdateGrupo(filter: ModelSubscriptionGrupoFilterInput, owner: String): Grupo @aws_subscribe(mutations: ["updateGrupo"]) @aws_iam @aws_cognito_user_pools
  onDeleteGrupo(filter: ModelSubscriptionGrupoFilterInput, owner: String): Grupo @aws_subscribe(mutations: ["deleteGrupo"]) @aws_iam @aws_cognito_user_pools
  onCreateCard(filter: ModelSubscriptionCardFilterInput, owner: String): Card @aws_subscribe(mutations: ["createCard"]) @aws_iam @aws_cognito_user_pools
  onUpdateCard(filter: ModelSubscriptionCardFilterInput, owner: String): Card @aws_subscribe(mutations: ["updateCard"]) @aws_iam @aws_cognito_user_pools
  onDeleteCard(filter: ModelSubscriptionCardFilterInput, owner: String): Card @aws_subscribe(mutations: ["deleteCard"]) @aws_iam @aws_cognito_user_pools
  onCreateLogActividad(filter: ModelSubscriptionLogActividadFilterInput, owner: String): LogActividad @aws_subscribe(mutations: ["createLogActividad"]) @aws_iam @aws_cognito_user_pools
  onUpdateLogActividad(filter: ModelSubscriptionLogActividadFilterInput, owner: String): LogActividad @aws_subscribe(mutations: ["updateLogActividad"]) @aws_iam @aws_cognito_user_pools
  onDeleteLogActividad(filter: ModelSubscriptionLogActividadFilterInput, owner: String): LogActividad @aws_subscribe(mutations: ["deleteLogActividad"]) @aws_iam @aws_cognito_user_pools
}

type ModelGrupoConnection @aws_iam @aws_cognito_user_pools {
  items: [Grupo]!
  nextToken: String
}

input ModelGrupoFilterInput {
  nombre: ModelStringInput
  materiaId: ModelIDInput
  adminId: ModelStringInput
  integrantes: ModelStringInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelGrupoFilterInput]
  or: [ModelGrupoFilterInput]
  not: ModelGrupoFilterInput
  owner: ModelStringInput
}

input ModelGrupoConditionInput {
  nombre: ModelStringInput
  materiaId: ModelIDInput
  adminId: ModelStringInput
  integrantes: ModelStringInput
  and: [ModelGrupoConditionInput]
  or: [ModelGrupoConditionInput]
  not: ModelGrupoConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  owner: ModelStringInput
}

input CreateGrupoInput {
  nombre: String!
  materiaId: ID!
  adminId: String!
  integrantes: [String]
  id: ID
}

input UpdateGrupoInput {
  nombre: String
  materiaId: ID
  adminId: String
  integrantes: [String]
  id: ID!
}

input DeleteGrupoInput {
  id: ID!
}

input ModelSubscriptionGrupoFilterInput {
  nombre: ModelSubscriptionStringInput
  materiaId: ModelSubscriptionIDInput
  adminId: ModelSubscriptionStringInput
  integrantes: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionGrupoFilterInput]
  or: [ModelSubscriptionGrupoFilterInput]
  owner: ModelStringInput
}

type ModelCardConnection @aws_iam @aws_cognito_user_pools {
  items: [Card]!
  nextToken: String
}

input ModelCardEstadoInput {
  eq: CardEstado
  ne: CardEstado
}

input ModelCardFilterInput {
  titulo: ModelStringInput
  descripcion: ModelStringInput
  estado: ModelCardEstadoInput
  orden: ModelIntInput
  grupoId: ModelIDInput
  adjuntos: ModelStringInput
  puntuacion: ModelIntInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelCardFilterInput]
  or: [ModelCardFilterInput]
  not: ModelCardFilterInput
  owner: ModelStringInput
}

input ModelCardConditionInput {
  titulo: ModelStringInput
  descripcion: ModelStringInput
  estado: ModelCardEstadoInput
  orden: ModelIntInput
  grupoId: ModelIDInput
  adjuntos: ModelStringInput
  puntuacion: ModelIntInput
  and: [ModelCardConditionInput]
  or: [ModelCardConditionInput]
  not: ModelCardConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  owner: ModelStringInput
}

input CreateCardInput {
  titulo: String!
  descripcion: String
  estado: CardEstado
  orden: Int
  grupoId: ID!
  adjuntos: [String]
  puntuacion: Int
  id: ID
}

input UpdateCardInput {
  titulo: String
  descripcion: String
  estado: CardEstado
  orden: Int
  grupoId: ID
  adjuntos: [String]
  puntuacion: Int
  id: ID!
}

input DeleteCardInput {
  id: ID!
}

input ModelSubscriptionCardFilterInput {
  titulo: ModelSubscriptionStringInput
  descripcion: ModelSubscriptionStringInput
  estado: ModelSubscriptionStringInput
  orden: ModelSubscriptionIntInput
  grupoId: ModelSubscriptionIDInput
  adjuntos: ModelSubscriptionStringInput
  puntuacion: ModelSubscriptionIntInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionCardFilterInput]
  or: [ModelSubscriptionCardFilterInput]
  owner: ModelStringInput
}

type ModelLogActividadConnection @aws_iam @aws_cognito_user_pools {
  items: [LogActividad]!
  nextToken: String
}

input ModelLogActividadFilterInput {
  grupoId: ModelIDInput
  usuarioId: ModelStringInput
  accion: ModelStringInput
  entidad: ModelStringInput
  entidadId: ModelStringInput
  timestamp: ModelIntInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelLogActividadFilterInput]
  or: [ModelLogActividadFilterInput]
  not: ModelLogActividadFilterInput
  owner: ModelStringInput
}

input ModelLogActividadConditionInput {
  grupoId: ModelIDInput
  usuarioId: ModelStringInput
  accion: ModelStringInput
  entidad: ModelStringInput
  entidadId: ModelStringInput
  timestamp: ModelIntInput
  and: [ModelLogActividadConditionInput]
  or: [ModelLogActividadConditionInput]
  not: ModelLogActividadConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  owner: ModelStringInput
}

input CreateLogActividadInput {
  grupoId: ID!
  usuarioId: String!
  accion: String!
  entidad: String!
  entidadId: String!
  timestamp: AWSTimestamp!
  id: ID
}

input UpdateLogActividadInput {
  grupoId: ID
  usuarioId: String
  accion: String
  entidad: String
  entidadId: String
  timestamp: AWSTimestamp
  id: ID!
}

input DeleteLogActividadInput {
  id: ID!
}

input ModelSubscriptionLogActividadFilterInput {
  grupoId: ModelSubscriptionIDInput
  usuarioId: ModelSubscriptionStringInput
  accion: ModelSubscriptionStringInput
  entidad: ModelSubscriptionStringInput
  entidadId: ModelSubscriptionStringInput
  timestamp: ModelSubscriptionIntInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionLogActividadFilterInput]
  or: [ModelSubscriptionLogActividadFilterInput]
  owner: ModelStringInput
}
